name: wheelimal
description: "Fortune wheel random selector app with minimalistic ui"
publish_to: 'none' 

version: 1.0.4+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_fortune_wheel: ^1.3.1
  rxdart: ^0.28.0
  provider:
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/wheel-of-fortune.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
